# Generated by Django 6.0.2 on 2026-03-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Фото')),
                ('scale', models.PositiveSmallIntegerField(choices=[(40, '40%'), (60, '60%'), (100, '100%')], default=100, verbose_name='Масштаб')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Фото кейса',
                'verbose_name_plural': 'Фото кейса',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
