# Generated by Django 6.0.2 on 2026-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(default='temp', max_length=200, unique=True, verbose_name='Ссылка (slug)'),
            preserve_default=False,
        ),
    ]
