# Generated by Django 6.0.2 on 2026-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_case_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['created_at'], 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AddField(
            model_name='case',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/cover/', verbose_name='Обложка для списка (avatar)'),
        ),
        migrations.AddField(
            model_name='case',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/desktop/', verbose_name='Картинка Desktop (macbook)'),
        ),
        migrations.AddField(
            model_name='case',
            name='desktop_text',
            field=models.TextField(blank=True, verbose_name='Текст блока Desktop'),
        ),
        migrations.AddField(
            model_name='case',
            name='execution_text',
            field=models.TextField(blank=True, verbose_name='Исполнение'),
        ),
        migrations.AddField(
            model_name='case',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/hero/', verbose_name='Главная картинка (фон сверху)'),
        ),
        migrations.AddField(
            model_name='case',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/mobile/', verbose_name='Картинка Mobile (iphone)'),
        ),
        migrations.AddField(
            model_name='case',
            name='mobile_text',
            field=models.TextField(blank=True, verbose_name='Текст блока Mobile'),
        ),
        migrations.AddField(
            model_name='case',
            name='mockup_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/mockup/', verbose_name='Mockup (большая картинка под кнопкой)'),
        ),
        migrations.AddField(
            model_name='case',
            name='result_text',
            field=models.TextField(blank=True, verbose_name='Достигнутый результат'),
        ),
        migrations.AddField(
            model_name='case',
            name='task_text',
            field=models.TextField(blank=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (под заголовком)'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(upload_to='cases/gallery/', verbose_name='Фото'),
        ),
    ]
