# Generated by Django 6.0.2 on 2026-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_case_options_case_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='caseimage',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Текст под фото'),
        ),
        migrations.AddField(
            model_name='caseimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок под фото'),
        ),
    ]
