# Generated by Django 6.0.2 on 2026-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_caseimage_caption_caseimage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cover_scale',
            field=models.PositiveSmallIntegerField(choices=[(40, '40%'), (60, '60%'), (100, '100%')], default=100, verbose_name='Масштаб обложки (для списка)'),
        ),
    ]
