# Generated by Django 6.0.2 on 2026-03-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_case_cover_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseimage',
            name='scale',
        ),
    ]
