# Generated by Django 6.0.2 on 2026-03-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_caseimage_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='scale',
            field=models.PositiveSmallIntegerField(choices=[(40, '40%'), (60, '60%'), (100, '100%')], default=100, verbose_name='Масштаб'),
        ),
    ]
