# Generated by Django 6.0.2 on 2026-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_caseimage_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt обложки'),
        ),
        migrations.AddField(
            model_name='case',
            name='home_position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Позиция на главной (1-3)'),
        ),
        migrations.AddField(
            model_name='case',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('show_on_home', True)), fields=('home_position',), name='uniq_home_position_when_show_on_home'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('home_position__in', [1, 2, 3]), ('home_position__isnull', True), _connector='OR'), name='check_home_position_1_3_or_null'),
        ),
    ]
