# Generated by Django 6.0.2 on 2026-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_case_cover_alt_case_home_position_case_show_on_home_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='case',
            name='uniq_home_position_when_show_on_home',
        ),
        migrations.RemoveConstraint(
            model_name='case',
            name='check_home_position_1_3_or_null',
        ),
        migrations.AlterField(
            model_name='case',
            name='home_position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Пустая позиция'), (1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Позиция на главной'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('show_on_home', True), ('home_position__in', [1, 2, 3])), fields=('home_position',), name='uniq_home_position_1_3_when_show_on_home'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('home_position__in', [0, 1, 2, 3]), ('home_position__isnull', True), _connector='OR'), name='check_home_position_0_3_or_null'),
        ),
    ]
