# Generated by Django 6.0.2 on 2026-03-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_case_uniq_home_position_when_show_on_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='show_on_works',
            field=models.BooleanField(default=True, verbose_name="Показывать на странице 'Наши проекты'"),
        ),
        migrations.AddField(
            model_name='case',
            name='works_block',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Блок на странице 'Наши проекты' (ряд)"),
        ),
        migrations.AddField(
            model_name='case',
            name='works_position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Пустая позиция'), (1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Позиция в блоке (1-3)'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('show_on_works', True), ('works_position__in', [1, 2, 3])), fields=('works_block', 'works_position'), name='uniq_works_block_pos_1_3_when_show_on_works'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('works_position__in', [0, 1, 2, 3]), ('works_position__isnull', True), _connector='OR'), name='check_works_position_0_3_or_null'),
        ),
    ]
