# Generated by Django 6.0.2 on 2026-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_case_show_on_works_case_works_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contact_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/contact/', verbose_name='Фон блока формы'),
        ),
        migrations.AddField(
            model_name='case',
            name='sphera_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/sphera/', verbose_name='Фон блока (sphera)'),
        ),
    ]
