# Generated by Django 6.0.2 on 2026-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_case_contact_bg_image_case_sphera_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='desktop_title_gradient',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Desktop заголовок (градиентная часть)'),
        ),
        migrations.AddField(
            model_name='case',
            name='desktop_title_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Desktop заголовок (обычная часть)'),
        ),
    ]
