# Generated by Django 6.0.2 on 2026-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_case_desktop_title_gradient_case_desktop_title_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='mobile_title_gradient',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Desktop заголовок (градиентная часть)'),
        ),
        migrations.AddField(
            model_name='case',
            name='mobile_title_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Desktop заголовок (обычная часть)'),
        ),
    ]
