# Generated by Django 6.0.2 on 2026-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_case_mobile_title_gradient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='case',
            name='mobile_text',
        ),
    ]
