# Generated by Django 6.0.2 on 2026-03-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_case_mobile_image_remove_case_mobile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMobileBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gradient', models.CharField(blank=True, max_length=80, null=True, verbose_name='Заголовок (градиент)')),
                ('title_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (текст)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/mobile/items/', verbose_name='Картинка')),
                ('layout', models.CharField(choices=[('image_left', 'Картинка слева, текст справа'), ('image_right', 'Картинка справа, текст слева')], default='image_right', max_length=20, verbose_name='Расположение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_blocks', to='main.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Моб. элемент',
                'verbose_name_plural': 'Моб. элементы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
