# Generated by Django 6.0.2 on 2026-03-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_casemobileblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='mobile_title_gradient',
        ),
        migrations.RemoveField(
            model_name='case',
            name='mobile_title_text',
        ),
    ]
