# Generated by Django 6.0.2 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_case_mobile_title_gradient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemobileblock',
            name='layout',
            field=models.CharField(choices=[('image_left', 'Картинка слева, текст справа'), ('image_right', 'Картинка справа, текст слева'), ('image_only', 'Оставить фото без текста')], default='image_right', max_length=20, verbose_name='Расположение'),
        ),
    ]
