# Generated by Django 6.0.2 on 2026-03-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_casemobileblock_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemobileblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/mobile/items/'),
        ),
        migrations.CreateModel(
            name='CaseMobileBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/mobile/items/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.casemobileblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
