# Generated by Django 6.0.2 on 2026-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_casemobileblock_image_casemobileblockimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='desktop_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/desktop/bg/', verbose_name='Фон блока Desktop'),
        ),
    ]
