# Generated by Django 6.0.2 on 2026-03-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_case_desktop_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/gallery/bg/', verbose_name='Фон блока'),
        ),
    ]
