# Generated by Django 6.0.2 on 2026-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_caseimage_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contact_bg_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt фона блока формы'),
        ),
        migrations.AddField(
            model_name='case',
            name='desktop_bg_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt фона блока Desktop'),
        ),
        migrations.AddField(
            model_name='case',
            name='desktop_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt картинки Desktop'),
        ),
        migrations.AddField(
            model_name='case',
            name='mockup_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt mockup'),
        ),
        migrations.AddField(
            model_name='case',
            name='sphera_bg_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt фона блока sphera'),
        ),
        migrations.AddField(
            model_name='caseimage',
            name='bg_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt фона блока'),
        ),
        migrations.AddField(
            model_name='caseimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt фото'),
        ),
        migrations.AddField(
            model_name='casemobileblock',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt картинки'),
        ),
        migrations.AddField(
            model_name='casemobileblockimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt картинки'),
        ),
    ]
